# Generated by Django 4.2.2 on 2023-07-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPizzaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dt_birth',
            new_name='date_birth',
        ),
    ]
