# Generated by Django 4.2.2 on 2023-07-01 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPizzaria', '0003_drink_menu_order_pizza_promotion_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='list_drinks',
            field=models.ManyToManyField(to='appPizzaria.drink'),
        ),
        migrations.AddField(
            model_name='menu',
            name='list_pizzas',
            field=models.ManyToManyField(to='appPizzaria.pizza'),
        ),
        migrations.AddField(
            model_name='menu',
            name='list_promotions',
            field=models.ManyToManyField(to='appPizzaria.promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appPizzaria.shoppingcart'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appPizzaria.user'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='drink',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appPizzaria.drink'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='pizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appPizzaria.pizza'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('drink', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appPizzaria.drink')),
                ('pizza', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appPizzaria.pizza')),
                ('promotion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appPizzaria.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(to='appPizzaria.item'),
        ),
    ]
